import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        {children}
        {modal}
      </body>
    </html>
  );
}
